### ISSUE TITLE
Doesn't recognize field types besides text

### ISSUE THREAD

**Issue by mrf** [chapter-three/require-to-publish#6]

**Comment by paboden** [comment]
This has been fixed by Rock's updates. Tested and works with:
- Textfield
- Textarea (with & without summary)
- Radio(s)
- Select Lists
- Checkbox(es)
- File/images
- Term reference

Still need to test with following fields:
- Link
- Node Reference
- Entity Reference
- Block Reference
- Date
- (and any additional fields that anyone can think of to test)

**Comment by dzink** [comment]
I've confirmed that this works for: Link, Entity Reference, Block Reference, Date, Node Reference, User Reference, Date. I have tried every widget type available to do so. Looks like this is fixed!
